apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: frontend
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-kyotong
        image: 192.168.22.62:30002/front/front:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-env
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: harbor-secret  # private registry 인증용, harbor-secret은 생성 필요